# Generated by Django 4.1.13 on 2024-03-28 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_alter_purchase_stripe_checkout_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='mpesa_code',
            new_name='mpesa_checkout_id',
        ),
    ]
