# Generated by Django 4.1.13 on 2024-03-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productimages_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
