# Generated by Django 4.1.13 on 2024-03-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productimages_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='mpesa_price',
        ),
        migrations.AddField(
            model_name='products',
            name='stripe_price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='products',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='og_price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=10),
        ),
    ]
