# Generated by Django 4.1.13 on 2024-03-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_products_mpesa_price_products_stripe_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='mpesa_price',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='products',
            name='mpesa_price_id',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='mpesa_product_id',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
