# Generated by Django 4.1.13 on 2024-03-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_products_mpesa_price_products_mpesa_price_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True, max_length=220, null=True),
        ),
    ]
